// Re-export all shared types from the canonical @simulacrum/types package.
// This file exists so that existing imports within the UI continue to work.
export type {
  Agent,
  AgentMode,
  AutonomyStatus,
  ClaimRecord,
  ClawdbotGoal,
  ClawdbotGoalStatus,
  ClawdbotMessage,
  ClawdbotNetworkStatus,
  ClawdbotProfile,
  InsurancePolicy,
  InsurancePool,
  Market,
  MarketBet,
  MarketBetsSnapshot,
  MarketChallenge,
  MarketOracleVote,
  MarketOrder,
  MarketResolution,
  MarketStatus,
  MarketSelfAttestation,
  OrderBookSnapshot,
  OrderSide,
  PolicyStatus,
  ReputationLeaderboardEntry,
  TrustEdge,
  TrustGraph,
  WsEvent,
  // Research types
  ResearchFocusArea,
  PublicationStatus,
  ObservationCategory,
  ResearchObservation,
  ObservationWindow,
  WindowSummary,
  ResearchAgentProfile,
  OnChainReference,
  PublicationFinding,
  ResearchPublication,
  EvalTest,
  EvalDimension,
  PublicationEvaluation,
  ResearchEngineStatus,
} from '@simulacrum/types'

export {
  RESEARCH_FOCUS_LABELS,
  RESEARCH_FOCUS_SHORT_LABELS,
} from '@simulacrum/types'
